### ISSUE TITLE
Can't get OpenAI GPT-4 as custom model

### ISSUE THREAD

**Issue by paradoxally** [wibus-wee/raycast-unblock#40]
### Describe the bug

I can't get OpenAI GPT-4 as a custom model in Raycast.

In my `config.toml` which is very similar to the example in this repo, I have the following:

```yml
# Custom OpenAI Model
id = "openai-gpt-4"
model = "gpt-4"
name = "GPT-4"
```

But they do not show up in the model section, as shown below:

<img width="1112" alt="CleanShot 2024-03-25 at 14 49 16@2x" src="https://github.com/wibus-wee/raycast-unblock/assets/1304041/4f6e4b0d-f2d1-404e-ad36-9240c6b1dbfb">

Is there a specific ID or model I am entering incorrectly? I would like to add both GPT-4 and GPT-4 Turbo as custom models. I have a key for GPT-4 so this isn't an issue, they just don't show up so I must be doing something wrong.

### Reproduction

Raycast Settings > AI tab > Model > Check if GPT-4 is there

### System Info

```Shell
System:
    OS: macOS 13.6.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 668.63 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.1 - /opt/homebrew/bin/node
    npm: 10.5.0 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 123.1.64.109
    Safari: 17.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by paradoxally** [comment]
Hi @wibus-wee,

That endpoint returns a 404 response.

**Comment by wibus-wee** [comment]
oh, I gave you the wrong url.

the right url is: `<your raycast unblock instance>/api/v1/ai/models`

**Comment by paradoxally** [comment]
Thanks. OpenAI GPT-4 is not in the models:

```json
{"default_models":{"chat":"openai-gpt-3.5-turbo","quick_ai":"openai-gpt-3.5-turbo","commands":"openai-gpt-3.5-turbo","api":"openai-gpt-3.5-turbo"},"models":[{"id":"openai-gpt-3.5-turbo","model":"gpt-3.5-turbo","name":"GPT-3.5 Turbo","provider":"openai","provider_name":"OpenAI","requires_better_ai":true,"features":["chat","quick_ai","commands","api"]},{"id":"gemini-pro","model":"gemini-pro","name":"Gemini Pro","provider":"gemini","provider_name":"Google","requires_better_ai":true,"features":["chat","quick_ai","commands","api"]},{"id":"copilot-gpt-3.5-turbo","model":"gpt-3.5-turbo","name":"Copilot GPT-3.5 Turbo","provider":"copilot","provider_name":"Github","requires_better_ai":true,"features":["chat","quick_ai","commands","api"]},{"id":"copilot-gpt-4","model":"gpt-4","name":"Copilot GPT-4","provider":"copilot","provider_name":"Github","requires_better_ai":true,"features":["chat","quick_ai","commands","api"]}]}
```

**Comment by wibus-wee** [comment]
Did you save and restart the configuration file after you modified it?

**Comment by paradoxally** [comment]
Yes, it's pulling my API key fine from the config file. That is why I keep thinking it's something wrong with ID or model I specified above.

**Comment by wibus-wee** [comment]
I can't seem to reproduce your problem.

```toml
[AI.OpenAI.Models.gpt-3_5-turbo-16k-legacy]
id = "gpt-3.5-turbo-16k.legacy" # if it's not provided, it will be generated from the Object key. For example, here it will be "gpt-3.5-turbo-16k-legacy"
model = "gpt-3.5-turbo-16k.legacy" # if it's not provided, it will be generated from the Object key.
name = "Legacy GPT-3.5 Turbo" # if it's not provided, it will be generated from the Object key.
```

![CleanShot 2024-03-27 at 23 33 55@2x](https://github.com/wibus-wee/raycast-unblock/assets/62133302/ba0c9071-9b56-465e-b81a-a1d89d23016b)

It runs fine on my computer. 🧐
