### ISSUE TITLE
求助 docker compose 配置文件不存在error

### ISSUE THREAD

**Issue by imoyy** [wibus-wee/raycast-unblock#50]
### Describe the bug

在前个版本时，使用docker运行本项目是正常运行的。
在最新版本中，我发现无论我将config.toml文件放在哪个位置，docker都会报错`error The configuration file [./configs/config.toml] doesn't exist.`，修改docker compose中的`volumes`或`--config`的路径，在运行docker后同样会报config.toml不存在的错误。
![CleanShot 2024-04-15 at 08 47 38@2x](https://github.com/wibus-wee/raycast-unblock/assets/115197762/9e762138-20e8-405d-bf45-035f0bc04f2d)
![CleanShot 2024-04-15 at 08 47 40@2x](https://github.com/wibus-wee/raycast-unblock/assets/115197762/a1c5ac69-7bd2-408c-8b32-ff6d0c69dd63)

### Reproduction

在docker compose文件目录下运行 `docker compose up -d`

### System Info

```Shell
docker logs 564f105b0df1
error The configuration file [./config.toml] doesn't exist.
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by imoyy** [comment]
在终端使用
```
docker run -d \
  --name raycast-unblock \
  -p 443:443 \
  -v ./config.toml:/app/config.toml \
  tmp-raycast
```
命令可以正常运行。这里的config.toml文件与 docker compose 文件中的路径相同。

**Comment by imoyy** [comment]
在终端运行
```
docker run -d \
  --name raycast-unblock \
  -p 443:443 \
  -v ./config.toml:/app/config.toml \
  wibuswee/raycast-unblock:latest
 ```
 docker run 命令可以正常运行，这里的config.toml文件和我在docker compose 文件中设置相同，运行的目录层级也相同。

**Comment by wibus-wee** [comment]
能看看你的docker-compose.yml吗

**Comment by imoyy** [comment]
> 能看看你的docker-compose.yml吗

好的，在这里
```yaml
version: '3.8'

services:
  app:
    container_name: raycast-unblock
    # ## You can also add arguments to the command line here, such as the following
    # ## If you need to use config.toml file, please uncomment the following line ####
    command: --config=./configs/config.toml
    image: wibuswee/raycast-unblock:latest
    environment:
      - TZ=Asia/Shanghai
      # ## You can also use proxy settings here, such as the following
      # - HTTP_PROXY=
      # - HTTPS_PROXY=
    # ## If you need to use config.toml file, please uncomment the following line ####
    volumes:
      - ./configs:/app/config
      # If you want to operate the Sync file, you can uncomment the following line
      # - ./raycast_sync:/root/raycast_sync
    ports:
      - '443:443'
    restart: always
    healthcheck:
      test: [CMD, curl, -f, 'http://127.0.0.1:443']
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 30s
```
